/**
 *
 */
import { readFileSync } from 'fs'
import { join } from 'path'
import findUp from 'find-up'


/**
 *
 */
const moduleName = 'kail'
const message = 'Generated by {{moduleName}}. Do not edit this file.'
const templatePath = join(__dirname, 'template.raw')


/**
 *
 */
export function isItself() {
  const gitPath = findUp.sync('.git')

  if (gitPath) {
    return gitPath.match(new RegExp(`${moduleName}/.git$`))
  }

  return false
}


/**
 *
 */
const content = readFileSync(templatePath, 'UTF-8')
  .replace('{{message}}', message)
  .replace(/{{moduleName}}/g, moduleName)
  .replace('{{hookRunner}}', isItself() ? './lib/index.js' : moduleName)


/**
 *
 */
export default { content, message }
